### PR TITLE
Put together a possible icon for grab-site

### PR DESCRIPTION
**Pull request by ethus3h**
I put together a possible icon for grab-site, using three libre-licensed sources. It's just an idea though, no need to use it if you don't like it :)

### CODE REVIEW

**Comment by ethus3h** [comment]
I'm not sure why it shows 4 commits, because I only want to pull-request one of them (https://github.com/ethus3h/grab-site/commit/ddf20705a707e3fb2aac4b68880040ebfee8c1e2)....

**Comment by ivan** [comment]
You generally want a new branch for every pull request; a PR includes all of the changes you've made on a branch.

I want to like your icon, but there's too much going on, grab-site won't necessarily be limited to WARC, and it makes it look like KDE1-era retroware :-)  Graphics are hard.

**Comment by ethus3h** [comment]
Hahah oh well XD

**Comment by ethus3h** [comment]
(I'm not anyone who knows anything about graphics really, just a random guy with inkscape)

**Pull request closed without merging**
