### PR TITLE
Make gs-server require a single port only

### PR DESCRIPTION
**Pull request by 12As**
I've changed the gs-server and other requisite files so that it only uses a single port.  I think it might be easier on people not to have to juggle two.  Feel free to close this if this clashes with your own plans or you'd rather implement something in a different way.

### CODE REVIEW

**Comment by ivan** [comment]
Assuming this works, very nice work.  It'd be nice to get rid of the aiohttp dependency.

**Comment by ivan** [comment]
Hmm, looking at `autobahn/websocket/protocol.py`, it looks like overriding `sendHtml` isn't suitable because it doesn't have the requested URL as an argument.

**Comment by ivan** [comment]
And working my way up the autobahn callstack, overriding `sendServerStatus` doesn't work either because it too lacks a `url` argument.

**Comment by ivan** [comment]
Please don't work on my review comments unless that main issue can be resolved: the ability to respond with a different page based on the request URL

**Comment by 12As** [comment]
The requested URL is available in the `sendHtml` or `sendServerStatus` through `self.http_request_uri`.  If you wanted to serve up responses for arbitrary requests, rather than the `dashboard.html` for all of them, then it might be better to do `sendServerStatus` and not the `sendHtml` one and call the latter with the html in question.

**Comment by ivan** [comment]
Ah, okay.  Then, for now, I think you can just add a check to make sure we're on "/", and for other URLs, either throw some exception or serve a tiny 404 page.

**Comment by 12As** [comment]
I believe I fixed the issues you cited.  Let me know if there is anything else you require.

**Comment by ivan** [comment]
When I tried this PR on my server, I noticed that none of my crawls were connecting to the new gs-server because it no longer listens on port 29001.  So I used `GRAB_SITE_PORT=29001` to make it start on that port instead, but that annoyingly breaks existing links and browser urlbar completion until it learns the new URL.  Not sure what to do about this; perhaps make `GRAB_SITE_PORT` take multiple ports like `29000,29001` and have a multi-month transition period before we stop listening on 29001?  Alternatively, we could break compatibility and document a local port forward, but that might make someone unhappy for requiring root.

**Comment by ivan** [comment]
(In general, grab-site is supposed to be work when upgraded even if you have crawls running from months ago.)

**Comment by ivan** [comment]
I'm working on this in a branch and hope to merge it soon

**Comment by ivan** [comment]
Merged, thank you!

**Comment by 12As** [comment]
I was going to implement those changes, but saw you already merged this in and did them.  I hope I didn't create too much work for you in any part of this process.  Also, if you want to clean up the commit history by squashing my commits or whatever else, feel free; no credit to me is necessary.  

Regardless, thank you for your constructive feedback and for creating this project.

**Pull request merged**
